receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  # Debug exporter (prints to stdout for testing)
  logging:
    loglevel: debug

  # Tempo (traces)
  otlp/tempo:
    endpoint: http://localhost:4317
    tls:
      insecure: true

  # Prometheus exporter (collector metrics about itself)
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Loki exporter (logs)
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]
